#!/usr/bin/R
# input data

codons <- data.frame( rbind(
        c("TTT", "F", "Phe"),
        c("TTC", "F", "Phe"),
        c("TTA", "L", "Leu"),
        c("TTG", "L", "Leu"),
        c("CTT", "L", "Leu"),
        c("CTC", "L", "Leu"),
        c("CTA", "L", "Leu"),
        c("CTG", "L", "Leu"),
        c("ATT", "I", "Ile"),
        c("ATC", "I", "Ile"),
        c("ATA", "I", "Ile"),
        c("ATG", "M", "Met"),
        c("GTT", "V", "Val"),
        c("GTC", "V", "Val"),
        c("GTA", "V", "Val"),
        c("GTG", "V", "Val"),
        c("TCT", "S", "Ser"),
        c("TCC", "S", "Ser"),
        c("TCA", "S", "Ser"),
        c("TCG", "S", "Ser"),
        c("CCT", "P", "Pro"),
        c("CCC", "P", "Pro"),
        c("CCA", "P", "Pro"),
        c("CCG", "P", "Pro"),
        c("ACT", "T", "Thr"),
        c("ACC", "T", "Thr"),
        c("ACA", "T", "Thr"),
        c("ACG", "T", "Thr"),
        c("GCT", "A", "Ala"),
        c("GCC", "A", "Ala"),
        c("GCA", "A", "Ala"),
        c("GCG", "A", "Ala"),
        c("TAT", "Y", "Tyr"),
        c("TAC", "Y", "Tyr"),
        c("TAA", "stop", "Ter"),
        c("TAG", "stop", "Ter"),
        c("CAT", "H", "His"),
        c("CAC", "H", "His"),
        c("CAA", "Q", "Gln"),
        c("CAG", "Q", "Gln"),
        c("AAT", "N", "Asn"),
        c("AAC", "N", "Asn"),
        c("AAA", "K", "Lys"),
        c("AAG", "K", "Lys"),
        c("GAT", "D", "Asp"),
        c("GAC", "D", "Asp"),
        c("GAA", "E", "Glu"),
        c("GAG", "E", "Glu"),
        c("TGT", "C", "Cys"),
        c("TGC", "C", "Cys"),
        c("TGA", "stop", "Ter"),
        c("TGG", "W", "Trp"),
        c("CGT", "R", "Arg"),
        c("CGC", "R", "Arg"),
        c("CGA", "R", "Arg"),
        c("CGG", "R", "Arg"),
        c("AGT", "S", "Ser"),
        c("AGC", "S", "Ser"),
        c("AGA", "R", "Arg"),
        c("AGG", "R", "Arg"),
        c("GGT", "G", "Gly"),
        c("GGC", "G", "Gly"),
        c("GGA", "G", "Gly"),
        c("GGG", "G", "Gly")
    ) )
names(codons) <- c("codon", "aacode", "aa")

synons <- setdiff( levels(codons$aa), c("Met","Trp","Ter") )
