#!/usr/bin/Rscript --vanilla
library(methods)
library(optparse)
library(pander)
library(ape)


scriptdir <-  dirname(sub("--file=","",commandArgs()[grep("--file",commandArgs())]))
source(file.path(scriptdir,"sim-context-fns.R"),chdir=TRUE)

usage <- '\
Convert an RData file to a Markdown file. \
Only meant to work for the RData files \
generated by this package.\
\
Run pandoc with `-f markdown-yaml_metadata_block`.
'

option_list <- list(
        make_option( c("-o","--outfile"), type="character", help="Write resulting Markdown to this file. Otherwise write to stdout." )
    )
cmd <- parse_args(OptionParser(option_list=option_list,description=usage), positional_arguments = TRUE)
opt <- cmd$options


### Functions

# le sigh.
n_hashes <- function(n) if(n > 0) paste0("#", n_hashes(n-1))

# Spit out the sorts of objects we care about in Markdown.
custom_pander <- function(x, sec_depth=1) {
    x_class = class(x)
    # First catch any S4 objects that want special treatment.
    if (x_class == "dgTMatrix" || x_class == "dgCMatrix") {
        pander(as.matrix(x))
    }
    else if (x_class == "DNAString") {
        pander(as.character(x))
    }
    else if (x_class == "simseq") {
        custom_pander(show.simseq(x))
    }
    else if (x_class == "phylo") {
        write.tree(x)
    }
    # S4 general treatment.
    else if (isS4(x)) {
        sapply(
            names(attributes(x)),
            function(name) {
                y <- slot(x, name)
                cat(n_hashes(sec_depth), name, ":", class(y), "\n")
                custom_pander(y, sec_depth+1)
            })
    }
    else if(x_class == "function") { }
    else if (x_class == "list") {
        if(length(x) > 0) pander(sapply(x, custom_pander))
    }
    else {
        if(length(x) > 0) pander(x)
    }
    cat("\n\n")
}


### "main"

out <- capture.output(
    lapply(
        cmd$args,
        function(fname) {
            stopifnot(grepl(".RData$", fname))
            names <- load(fname)
            lapply(
                names,
                function(name) {
                    cat("#", name, "\n")
                    custom_pander(get(name), 2)
                })
        }))

die.die.die = if(is.null(opt$outfile)) { cat(out, sep="\n") } else { cat(out, file=opt$outfile, sep="\n")}

