from SCons.Script import VariantDir, Environment, Builder, Depends, Flatten
import os

VariantDir('_build', src_dir='.')

env = Environment(ENV=os.environ)
inkscape = Builder(action = 'inkscape --without-gui --export-pdf=$TARGET $SOURCE')
env['BUILDERS']['Inkscape'] = inkscape
env['BUILDERS']['Latexdiff'] = Builder(action = 'latexdiff $SOURCES > $TARGET')

svgs = [ ]

pdfs = [env.Inkscape(target="_build/" + os.path.basename(svg).replace('.svg','.pdf'), source=svg)
        for svg in svgs] + [
          "../writeup-plots/selsims-2013-06-03-13-17-0790276-mutrates.pdf"
        ]

context_dependence, = env.PDF(target='_build/context-dependence.pdf',source='context-dependence.tex')
Default(context_dependence)

#env.Latexdiff(target='diff.tex',source=['stored_context-dependence.tex','context-dependence.tex'])
#diff = env.PDF(target='diff.pdf',source='diff.tex')

Depends(Flatten([context_dependence]),
        Flatten([pdfs, 'context-dependence.bib']))

cont_build = env.Command('.continuous', ['context-dependence.bib', 'context-dependence.tex'],
    'while :; do inotifywait -e modify $SOURCES; scons -Q; done')
Alias('continuous', cont_build)
