#PBS -S /bin/bash
#PBS -q cmb
#PBS -N bcells-inference
#PBS -l nodes=1:ppn=1
#PBS -l walltime=120:00:00
#PBS -l pmem=4gb
#PBS -l mem=500mb
#PBS -l vmem=5gb
# #PBS -e qsub-logs
# #PBS -o qsub-logs

# USAGE:
#    qsub -vARGS="bcells-inference.R -u 02-C-M_out_of_frame -w 2 -l 2 -r 2 -k 2" skeleton.pbs

source /usr/usc/R/3.0.2/setup.sh

cd /home/rcf-40/pralph/panfs/context/bcells

echo "$ARGS"

Rscript $ARGS

exit

